### ISSUE TITLE
chore(publish): whitelist folder/files needed to be published

### ISSUE THREAD

**Issue by GervinFung** [chandru89new/switch-case#1]
Hey, I noticed that this repository did not whitelist only those folders or files that need to be published, resulting in a 'fatter' package, see below

![image](https://user-images.githubusercontent.com/53143214/186485538-ccd704ce-c242-4723-9f84-a88d56b67607.png)

With whitelisting, it should be

![image](https://user-images.githubusercontent.com/53143214/186486008-4e0d6820-6a15-4779-bdab-e93c145d9922.png)

The published packages should only contain `dist` and `package.json` to work, with `LICENSE` and `readme` being the exceptions as it's included by default

If you don't mind, I will do the whitelisting part

**Comment by chandru89new** [comment]
Oh wow never occurred to me at all as I was in the Github mode of things. Thanks for the catch! Please feel free to raise a PR!
